// REPOSITORIES
export const INJECTION_REPOSITORY_USER = '@INJECTION_REPOSITORY_USER';

//SERVICES
export const INJECTION_SERVICE_CREATE_USER = '@INJECTION_SERVICE_CREATE_USER';
export const INJECTION_SERVICE_FINDBY_USER = '@INJECTION_SERVICE_FINDBY_USER';
export const INJECTION_SERVICE_AUTH = '@INJECTION_SERVICE_AUTH';

// USE CASES
export const INJECTION_USECASE_CREATE_USER = '@INJECTION_USECASE_CREATE_USER';
export const INJECTION_USECASE_FINDBY_USER = '@INJECTION_USECASE_CREATE_USER';
export const INJECTION_USECASE_AUTH = '@INJECTION_USECASE_AUTH';
